
const scored=games.filter(g=>g.score!=null),withHours=games.filter(g=>g.hours!=null),totalHours=withHours.reduce((n,g)=>n+g.hours,0),avgScore=scored.reduce((n,g)=>n+g.score,0)/scored.length,ninePlus=scored.filter(g=>g.score>=9).length,mostPlayed=[...withHours].sort((a,b)=>b.hours-a.hours)[0],highest=Math.max(...scored.map(g=>g.score)),highestGames=scored.filter(g=>g.score===highest),tagCounts=games.flatMap(g=>g.tags||[]).reduce((m,t)=>(m[t]=(m[t]||0)+1,m),{}),topTag=Object.entries(tagCounts).sort((a,b)=>b[1]-a[1])[0];document.querySelector('#statsGrid').innerHTML=`<div class="stat-box"><b>${games.length}</b><span>Total Games</span></div><div class="stat-box"><b>${Math.round(totalHours).toLocaleString()}+</b><span>Hours Played</span></div><div class="stat-box"><b>${avgScore.toFixed(1)}/10</b><span>Average Score</span></div><div class="stat-box"><b>${ninePlus}</b><span>Rated 9+</span></div><div class="stat-box stat-wide"><b>${mostPlayed.title}</b><span>Most Played • ${mostPlayed.hours} hours</span></div><div class="stat-box stat-wide"><b>${highestGames.map(g=>g.title).slice(0,2).join(' • ')}</b><span>Highest Rated • ${highest}/10</span></div><div class="stat-box"><b>${topTag[0]}</b><span>Most Common Tag</span></div>`;
const grid=document.querySelector('#grid'),search=document.querySelector('#search'),modal=document.querySelector('#modal'),review=document.querySelector('#review'),resultCount=document.querySelector('#resultCount'),sort=document.querySelector('#sort'),tagFilter=document.querySelector('#tagFilter');let filter='all';
const allTags=[...new Set(games.flatMap(g=>g.tags||[]))].sort((a,b)=>a.localeCompare(b));tagFilter.innerHTML+=[...allTags].map(t=>`<option value="${t}">${t}</option>`).join('');
const reviewed=games.filter(g=>g.status==='reviewed');document.querySelector('#reviewCount').textContent=reviewed.length;
function card(g){return `<article class="card ${g.status}" data-title="${g.title.replaceAll('"','&quot;')}"><div class="cover ${g.appId?'has-artwork':''}">${g.appId?`<img src="https://cdn.akamai.steamstatic.com/steam/apps/${g.appId}/header.jpg" alt="${g.title} artwork" loading="lazy" onerror="this.remove();this.parentElement.classList.remove(\'has-artwork\')">`:`<div class="cover-mark">YG</div><div class="cover-title">${g.title}</div>`}</div><div class="card-body">${g.status==='reviewed'?'<p class="eyebrow">REVIEWED</p>':''}<h3>${g.title}</h3><div class="hours">🎮 ${g.hours!=null?g.hours+' hours played':'Playtime not recorded'}</div><div class="tag-row library-tags">${(g.tags||[]).map(t=>`<span class="tag-link" data-tag="${t}">${t}</span>`).join('')}</div>${g.score?`<div class="score">${g.score}/10</div>`:'<div class="status">Review coming soon</div>'}</div></article>`}
function render(){let q=search.value.trim().toLowerCase();let list=games.filter(g=>g.title.toLowerCase().includes(q));if(tagFilter.value!=='all')list=list.filter(g=>(g.tags||[]).includes(tagFilter.value));if(filter==='reviewed')list=list.filter(g=>g.status==='reviewed');if(filter==='coming')list=list.filter(g=>g.status!=='reviewed');if(filter==='most')list=list.filter(g=>g.hours!=null).sort((a,b)=>b.hours-a.hours).slice(0,25);else{
const mode=sort.value;
if(mode==='playtime-desc')list.sort((a,b)=>(b.hours??-1)-(a.hours??-1));
if(mode==='playtime-asc')list.sort((a,b)=>(a.hours??Infinity)-(b.hours??Infinity));
if(mode==='score-desc')list.sort((a,b)=>(b.score??-1)-(a.score??-1)||a.title.localeCompare(b.title));
if(mode==='score-asc')list.sort((a,b)=>(a.score??Infinity)-(b.score??Infinity)||a.title.localeCompare(b.title));
if(mode==='title-asc')list.sort((a,b)=>a.title.localeCompare(b.title));
if(mode==='title-desc')list.sort((a,b)=>b.title.localeCompare(a.title));
}resultCount.textContent=`Showing ${list.length} of ${games.length} imported games`;grid.innerHTML=list.map(card).join('')||'<p class="empty">No games found.</p>';document.querySelectorAll('.card.reviewed').forEach(c=>c.onclick=()=>openReview(games.find(g=>g.title===c.dataset.title)));document.querySelectorAll('.library-tags .tag-link').forEach(b=>b.onclick=e=>{e.stopPropagation();tagFilter.value=b.dataset.tag;render();document.querySelector('#games').scrollIntoView({behavior:'smooth',block:'start'})})}
const SUPABASE_URL='https://swhwuxhnmjthfefmnluk.supabase.co';
const SUPABASE_KEY='sb_publishable_x7wKBCsTVdTjcleUCcxDIA_PplBagDb';
function reviewGameId(g){return g.appId?String(g.appId):g.title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function voterId(){let id=localStorage.getItem('yg_review_voter');if(!id){id=crypto.randomUUID();localStorage.setItem('yg_review_voter',id)}return id}
async function voteRequest(path,options={}){const headers={apikey:SUPABASE_KEY,Authorization:'Bearer '+SUPABASE_KEY,...(options.headers||{})};const res=await fetch(SUPABASE_URL+'/rest/v1/'+path,{...options,headers});if(!res.ok)throw new Error(await res.text());return res.status===204?null:res.json()}
async function loadVotes(g){const box=document.querySelector('#reviewVoteBox');if(!box)return;const gameId=reviewGameId(g),me=voterId();try{const rows=await voteRequest('review_votes?game_id=eq.'+encodeURIComponent(gameId)+'&select=vote,voter_id');const likes=rows.filter(v=>v.vote==='like').length,dislikes=rows.filter(v=>v.vote==='dislike').length,mine=rows.find(v=>v.voter_id===me)?.vote;box.querySelector('[data-vote="like"] .vote-count').textContent=likes;box.querySelector('[data-vote="dislike"] .vote-count').textContent=dislikes;box.querySelectorAll('.vote-btn').forEach(b=>b.classList.toggle('selected',b.dataset.vote===mine));box.querySelector('.vote-note').textContent=mine?'Thanks for your feedback.':'One vote per review.'}catch(e){box.querySelector('.vote-note').textContent='Voting is temporarily unavailable.'}}
async function castVote(g,vote){const box=document.querySelector('#reviewVoteBox');if(!box)return;const gameId=reviewGameId(g),me=voterId();box.querySelectorAll('.vote-btn').forEach(b=>b.disabled=true);try{const mine=await voteRequest('review_votes?game_id=eq.'+encodeURIComponent(gameId)+'&voter_id=eq.'+encodeURIComponent(me)+'&select=vote');if(mine.length){if(mine[0].vote!==vote)await voteRequest('review_votes?game_id=eq.'+encodeURIComponent(gameId)+'&voter_id=eq.'+encodeURIComponent(me),{method:'PATCH',headers:{'Content-Type':'application/json','x-voter-id':me,Prefer:'return=minimal'},body:JSON.stringify({vote})})}else await voteRequest('review_votes',{method:'POST',headers:{'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify({game_id:gameId,vote,voter_id:me})});await loadVotes(g)}catch(e){box.querySelector('.vote-note').textContent='Could not save your vote. Please try again.'}finally{box.querySelectorAll('.vote-btn').forEach(b=>b.disabled=false)}}
function openReview(g){const r=g.review||{};const section=(title,text)=>text?`<h3>${title}</h3><p>${text}</p>`:'';review.innerHTML=`<div class="review">${g.appId?`<div class="review-hero"><img src="https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/${g.appId}/header.jpg" alt="${g.title} artwork" onerror="this.parentElement.remove()"></div>`:''}<div class="review-heading"><div><p class="eyebrow">MY REVIEW • ${g.hours!=null?g.hours+' HOURS PLAYED':'PLAYTIME NOT RECORDED'}</p><h2>${g.title}</h2><div class="tag-row review-tags">${(g.tags||[]).map(t=>`<span>${t}</span>`).join('')}</div></div><div class="bigscore">${g.score}/10</div></div>${section('What I liked',r.liked)}${section("What I didn't like",r.disliked)}${section('Story',r.story)}${section('Combat & Gameplay',r.combat)}${section('Exploration & Open World',r.exploration)}${section('Building & Customization',r.building)}${section('Comparison',r.comparison)}${section('Who I Recommend It To',r.recommendation)}${section('Final Thoughts',r.verdict)}<div class="review-votes" id="reviewVoteBox"><div><strong>Was this review helpful?</strong><span class="vote-note">Loading votes…</span></div><div class="vote-actions"><button class="vote-btn" data-vote="like" aria-label="Like this review">👍 <span class="vote-count">0</span></button><button class="vote-btn" data-vote="dislike" aria-label="Dislike this review">👎 <span class="vote-count">0</span></button></div></div></div>`;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.querySelectorAll('#reviewVoteBox .vote-btn').forEach(b=>b.onclick=()=>castVote(g,b.dataset.vote));loadVotes(g)}
const bestReviews=reviewed.filter(g=>g.score>=9).sort((a,b)=>b.score-a.score||b.hours-a.hours);const featured=bestReviews[Math.floor(Math.random()*bestReviews.length)];document.querySelector('#latestReview').innerHTML=featured?`<div><span class="pill">${featured.score}/10</span><h2>${featured.title}</h2><p>${featured.review.liked}</p><button id="latestBtn">Read my review</button></div><div class="spot-score">${featured.score}</div>`:'No 9/10+ reviews yet';if(featured)document.querySelector('#latestBtn').onclick=()=>openReview(featured);
search.oninput=render;sort.onchange=render;tagFilter.onchange=render;document.querySelectorAll('.filters button').forEach(b=>b.onclick=()=>{document.querySelector('.filters .active').classList.remove('active');b.classList.add('active');filter=b.dataset.filter;render()});document.querySelector('#close').onclick=()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true')};modal.onclick=e=>{if(e.target===modal)document.querySelector('#close').click()};document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelector('#close').click()});render();
const wishlist=[
{title:"Crimson Desert Enhanced",appId:"3321460",release:"Mar 19, 2026",tags:["Open World","Singleplayer","Action","Exploration","Adventure"],status:"Waiting to Play"},
{title:"CONTROL Resonant",artwork:"https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/3669870/1e0c76e4253d347bb1304c3f213570251d924edf/header.jpg?t=1790259464",appId:"3669870",release:"Sep 24, 2026",tags:["Hack and Slash","Action RPG","Story Rich","Lore-Rich","Supernatural"],status:"Waiting to Play"},
{title:"The Last of Us™ Part II Remastered",appId:"2531310",release:"Apr 3, 2025",tags:["Story Rich","Post-apocalyptic","Third-Person Shooter","Action-Adventure","LGBTQ+"],status:"Waiting to Play"},
{title:"Indiana Jones and the Great Circle",artwork:"https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2677660/151ae5a881f05ef630defef85d99b38146b7055c/header.jpg?t=1778168392",appId:"2677660",release:"Dec 8, 2024",tags:["Action-Adventure","First-Person","Story Rich","Puzzle","Singleplayer"],status:"Waiting to Play"},
{title:"007 First Light",appId:"3768760",release:"May 26, 2026",tags:["Cinematic","Story Rich","Singleplayer","Espionage","Action-Adventure"],status:"Waiting to Play"},
{title:"PRAGMATA",appId:"3357650",release:"Apr 17, 2026",tags:["Cute","Sci-fi","Action","Third-Person Shooter","Funny"],status:"Waiting to Play"},
{title:"Hell is Us",appId:"1620730",release:"Sep 4, 2025",tags:["Action","Singleplayer","Adventure","Atmospheric","Third Person"],status:"Waiting to Play"},
{title:"Path of Exile 2",artwork:"https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2694490/24eeddcbda17903f03d819588757e40845f8115f/header.jpg?t=1787697213",appId:"2694490",release:"Dec 6, 2024",tags:["Action RPG","Hack and Slash","RPG","Loot","Isometric"],status:"Waiting to Play"},
{title:"The Outer Worlds 2",artwork:"https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1449110/fe273e39cbaf4997d1c8e53879800f07dba0ee03/header.jpg?t=1761760147",appId:"1449110",release:"Oct 29, 2025",tags:["RPG","Singleplayer","Action RPG","Open World","Exploration"],status:"Waiting to Play"},
{title:"METRO 2039",artwork:"https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2590240/6998fb70f896b0f155061de0b472a8262bd06ef9/header.jpg?t=1788444240",appId:"2590240",release:"Feb 4, 2027",tags:["Action","Adventure","Post-apocalyptic","FPS","Shooter"],status:"Waiting for Release"},
{title:"The Expanse: Osiris Reborn",artwork:"https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3727390/29369846b5ba94b2b1620eb8dd5aa8488f058d90/header.jpg?t=1777035417",appId:"3727390",release:"Q2 2027",tags:["Action","RPG","Sci-fi","Singleplayer","Story Rich"],status:"Waiting for Release"},
{title:"EXODUS",artwork:"https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/3230960/c7daff445142b7d24677b2e962bd84314da0b813/header.jpg?t=1787683475",appId:"3230960",release:"Apr 7, 2027",tags:["Story Rich","Cinematic","Action RPG","Singleplayer","Adventure"],status:"Waiting for Release"}
];
function wishlistCard(g){return `<article class="card wishlist-card"><div class="wishlist-cover has-artwork"><img src="${g.artwork||`https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/${g.appId}/header.jpg`}" alt="${g.title} artwork" loading="lazy" onerror="this.remove();this.parentElement.classList.remove('has-artwork')"><div class="cover-mark">WISHLIST</div><div class="cover-title">${g.title}</div></div><div class="card-body"><p class="eyebrow">${g.status.toUpperCase()}</p><h3>${g.title}</h3><div class="release">Release: ${g.release}</div><div class="tag-row">${g.tags.slice(0,3).map(t=>`<span>${t}</span>`).join('')}</div><div class="status wishlist-status">PLAY • THEN REVIEW</div></div></article>`}
document.querySelector('#wishlistGrid').innerHTML=wishlist.map(wishlistCard).join('');

const backToTop=document.querySelector('#backToTop');window.addEventListener('scroll',()=>backToTop.classList.toggle('show',window.scrollY>500),{passive:true});backToTop.onclick=()=>window.scrollTo({top:0,behavior:'smooth'});
